# Generated by Django 3.2.15 on 2022-11-04 09:48

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_orderdata_orderproducts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdata',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderproducts',
            options={'verbose_name': 'Элемент заказа', 'verbose_name_plural': 'Элементы заказа'},
        ),
        migrations.AddField(
            model_name='orderdata',
            name='address',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=250, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdata',
            name='first_name',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=50, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdata',
            name='last_name',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=50, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, verbose_name='Телефон'),
        ),
    ]
