# Generated by Django 3.2.15 on 2022-11-04 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20221104_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducts',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elements', to='foodcartapp.product', verbose_name='продукт'),
        ),
    ]
