# Generated by Django 3.2.15 on 2022-11-06 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_alter_orderproducts_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdata',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='orderdata',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='orderdata',
            old_name='phone_number',
            new_name='phonenumber',
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='foodcartapp.orderdata', verbose_name='элемент заказа'),
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='foodcartapp.product', verbose_name='продукт'),
        ),
    ]
