# Generated by Django 3.2.15 on 2022-11-09 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_alter_orderproducts_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orderproducts',
            managers=[
            ],
        ),
    ]
