# Generated by Django 3.2.15 on 2023-01-14 21:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20230114_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='called_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата звонка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdata',
            name='delivered_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 1, 14, 21, 28, 1, 56996, tzinfo=utc), verbose_name='Дата доставки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdata',
            name='registered_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
