# Generated by Django 3.2.15 on 2023-02-11 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_auto_20230128_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdata',
            name='status',
            field=models.CharField(choices=[('Принят', 'Принят'), ('Готовится', 'Готовится'), ('Доставка', 'Доставка'), ('Выполнен', 'Выполнен')], db_index=True, default='Принят', max_length=25, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(1)], verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(1)], verbose_name='цена'),
        ),
    ]
