# Generated by Django 3.2.15 on 2023-02-14 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_auto_20230214_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdata',
            old_name='restaurant',
            new_name='cooking_restaurant',
        ),
    ]
