# Generated by Django 3.2.15 on 2023-02-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_auto_20230216_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Наличными', 'Наличными'), ('Электронно', 'Электронно')], db_index=True, default=None, max_length=25, null=True, verbose_name='Способ оплаты'),
        ),
    ]
